In [ ]:
#pip install scikit-learn
#pip install lightgbm

In [9]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split
import lightgbm as lgb
from sklearn.metrics import accuracy_score, classification_report

In [2]:
data = pd.read_csv("/Users/farhat/Documents/Project/ProcessedData/fullData.csv")
data.head(10)

HR  O2Sat   Temp     SBP   MAP    DBP  Resp  EtCO2  BaseExcess  HCO3  \
0  80.0  100.0  36.50  121.00  58.0  41.00  13.5    NaN         1.0  25.0   
1  76.0  100.0  36.25  113.25  61.0  41.50  12.0    NaN         1.0  25.0   
2  80.0  100.0  36.25  132.75  71.5  46.25  12.0    NaN         1.0  25.0   
3  78.0  100.0  36.10  103.50  58.0  43.00  12.0    NaN        -3.0  25.0   
4  74.0  100.0  36.00  128.75  69.5  44.50  12.5    NaN        -3.0  25.0   
5  76.0  100.0  36.20  124.00  65.0  41.50  14.0    NaN         0.0  25.0   
6  70.0  100.0  36.10  120.25  65.0  43.00  14.0    NaN         0.0  25.0   
7  67.0  100.0  36.40  130.50  73.0  49.00  14.0    NaN         0.0  25.0   
8  64.5  100.0  36.55  116.75  62.5  42.50  14.0    NaN         0.0  25.0   
9  65.0   99.0  36.90  117.50  61.0  43.50  21.0    NaN         0.0  24.0   

   ...    Age  Gender  Unit1  Unit2  HospAdmTime  ICULOS  ShockIndex  BUN_CR  \
0  ...  77.27       1    0.0    1.0       -69.14       3    0.661157     NaN   
1  ...  77.27       1    0.0    1.0       -69.14       4    0.671082     NaN   
2  ...  77.27       1    0.0    1.0       -69.14       5    0.602637     NaN   
3  ...  77.27       1    0.0    1.0       -69.14       6    0.753623     NaN   
4  ...  77.27       1    0.0    1.0       -69.14       7    0.574757     NaN   
5  ...  77.27       1    0.0    1.0       -69.14       8    0.612903     NaN   
6  ...  77.27       1    0.0    1.0       -69.14       9    0.582121     NaN   
7  ...  77.27       1    0.0    1.0       -69.14      10    0.513410     NaN   
8  ...  77.27       1    0.0    1.0       -69.14      11    0.552463     NaN   
9  ...  77.27       1    0.0    1.0       -69.14      12    0.553191     NaN   

   PartialSOFA  SepsisLabel  
0          3.0            0  
1          3.0            0  
2          2.0            0  
3          3.0            0  
4          3.0            0  
5          3.0            0  
6          3.0            0  
7          2.0            0  
8          3.0            0  
9          3.0            0  

[10 rows x 44 columns]

In [3]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]
X.head()

HR  O2Sat   Temp     SBP   MAP    DBP  Resp  EtCO2  BaseExcess  HCO3  \
0  80.0  100.0  36.50  121.00  58.0  41.00  13.5    NaN         1.0  25.0   
1  76.0  100.0  36.25  113.25  61.0  41.50  12.0    NaN         1.0  25.0   
2  80.0  100.0  36.25  132.75  71.5  46.25  12.0    NaN         1.0  25.0   
3  78.0  100.0  36.10  103.50  58.0  43.00  12.0    NaN        -3.0  25.0   
4  74.0  100.0  36.00  128.75  69.5  44.50  12.5    NaN        -3.0  25.0   

   ...  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  ICULOS  \
0  ...      160.0  77.27       1    0.0    1.0       -69.14       3   
1  ...      160.0  77.27       1    0.0    1.0       -69.14       4   
2  ...      160.0  77.27       1    0.0    1.0       -69.14       5   
3  ...      160.0  77.27       1    0.0    1.0       -69.14       6   
4  ...      160.0  77.27       1    0.0    1.0       -69.14       7   

   ShockIndex  BUN_CR  PartialSOFA  
0    0.661157     NaN          3.0  
1    0.671082     NaN          3.0  
2    0.602637     NaN          2.0  
3    0.753623     NaN          3.0  
4    0.574757     NaN          3.0  

[5 rows x 43 columns]

In [4]:
# Assuming you have X (features) and y (target)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
print (X_train.shape)
print (X_test.shape)
print (y_train.shape)
print (y_test.shape)

(632172, 43)
(158043, 43)
(632172,)
(158043,)


In [6]:
# LightGBM Dataset
train_data = lgb.Dataset(X_train, label=y_train)

# Parameters
params = {
    'objective': 'binary',
    'metric': 'binary_logloss',
    'verbose': -1
}

# Train the model
model = lgb.train(params, train_data, num_boost_round=50)

In [12]:
y_pred = model.predict(X_test)
y_pred = (y_pred >= 0.5).astype(int)

y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(158043,))

In [13]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))


Accuracy: 0.9793410654062502
              precision    recall  f1-score   support

           0       0.98      1.00      0.99    154566
           1       0.75      0.09      0.16      3477

    accuracy                           0.98    158043
   macro avg       0.86      0.55      0.58    158043
weighted avg       0.97      0.98      0.97    158043



In [15]:
from sklearn.metrics import confusion_matrix

In [16]:
confusion_matrix(y_test,y_pred=y_pred)

array([[154457,    109],
       [  3156,    321]])

In [25]:
np.unique(y_test, return_counts=True)

(array([0, 1]), array([154566,   3477]))

In [21]:
print (y_test)
print (y_pred)

70024     0
181934    0
724581    0
199837    0
581915    0
         ..
665469    0
452072    0
493677    0
536585    0
405136    0
Name: SepsisLabel, Length: 158043, dtype: int64
[0 0 0 ... 0 0 0]


In [22]:
pd.DataFrame({
    'Sepsis Label' : y_test,
    'Sepsis Predicted':y_pred
})

Sepsis Label  Sepsis Predicted
70024              0                 0
181934             0                 0
724581             0                 0
199837             0                 0
581915             0                 0
...              ...               ...
665469             0                 0
452072             0                 0
493677             0                 0
536585             0                 0
405136             0                 0

[158043 rows x 2 columns]

In [19]:


dtrain = lgb.Dataset(X_train, label=y_train)

params = {
    'objective': 'binary',
    'metric': 'binary_logloss',
    'verbose': -1
}

# 5-fold CV
cv_results = lgb.cv(params, dtrain, num_boost_round=100, nfold=5, stratified=True, shuffle=True, seed=42)

# View results
print("Best log loss:", cv_results.keys())


Best log loss: dict_keys(['valid binary_logloss-mean', 'valid binary_logloss-stdv'])
